version: "3"

services:
  djangocrud:
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:5000"
    ports:
      - "5000:5000"
    restart: always

